object Versions {
    const val material3 = "1.0.0-beta01"
    const val compose = "1.3.0"
    const val composeUi = "1.2.1"
    const val room = "2.4.3"
    const val hilt = "2.42"
    const val lifecycle = "2.6.0-alpha01"
    const val accompanist = "0.26.1-alpha"
    const val jUnit = "4.13.2"
    const val androidxHilt = "1.0.0"
    const val navigation = "2.5.1"
    const val uiDebug = "1.2.1"
    const val activity = "1.5.1"
    const val lifecycleRuntime = "2.5.1"
    const val core = "1.8.0"
    const val espresso = "3.4.0"
    const val googleFonts = "1.3.0-beta01"
    const val icons = "1.2.0"
    const val dataStore = "1.0.0"
    const val moshi = "1.13.0"
    const val appCompat = "1.5.0"
    const val material = "1.6.1"
}